import { networkJudge } from 'network-judge'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log({ networkJudge })
  networkJudge()
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
