name: General CI

on:
  pull_request:
jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.8.1
      - name: Run Biome
        run: biome ci --reporter=github --diagnostic-level=error --error-on-warnings .

  testing:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: npm i -g pm2
      - name: test
        run: npm run test
